meta:
  environment: consul-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

jobs:
  - name: consul_bootstrap_z1
    instances: 1
    networks:
      - name: consul1
        static_ips: (( static_ips(0) ))
  - name: consul_server_z1
    instances: 2
    networks:
      - name: consul1
        static_ips: (( static_ips(1, 2) ))
    properties:
      consul:
        bootstrap_address: (( jobs.consul_bootstrap_z1.networks.consul1.static_ips.[0] ))
        servers: (( jobs.consul_server_z1.networks.consul1.static_ips ))
  - name: consul_client_z1
    instances: 0
    networks:
      - name: consul1
    properties:
      consul:
        bootstrap_address: (( jobs.consul_bootstrap_z1.networks.consul1.static_ips.[0] ))
        servers: (( jobs.consul_server_z1.networks.consul1.static_ips ))


compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: consul1
  # Assumes up to 5 VMs, including 3 static and 2 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.4.0/30
    reserved:
    - 10.244.4.1
    static:
    - 10.244.4.2
  - cloud_properties:
      name: random
    range: 10.244.4.4/30
    reserved:
    - 10.244.4.5
    static:
    - 10.244.4.6
  - cloud_properties:
      name: random
    range: 10.244.4.8/30
    reserved:
    - 10.244.4.9
    static:
    - 10.244.4.10

  - cloud_properties:
      name: random
    range: 10.244.4.12/30
    reserved:
    - 10.244.4.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.16/30
    reserved:
    - 10.244.4.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.4.20/30
    reserved:
    - 10.244.4.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.24/30
    reserved:
    - 10.244.4.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.28/30
    reserved:
    - 10.244.4.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.32/30
    reserved:
    - 10.244.4.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.36/30
    reserved:
    - 10.244.4.37
    static: []
