meta:
  environment: ~

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: true

jobs:
  - name: consul_bootstrap_z1
    templates:
      - name: consul
        release: consul
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
  - name: consul_server_z1
    template: consul
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties:
      consul:
        server: true
        servers: ~
    persistent_disk: 0

networks: (( merge ))

properties: {}
