meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: consul_bootstrap_z1
    template: consul
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
  - name: consul_server_z1
    template: consul
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      consul:
        server: true
        servers: ~
  - name: consul_client_z1
    template: consul
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      consul:
        servers: ~

networks: (( merge ))

properties: {}
