meta:
  environment: ~

update:
  canaries: 0
  max_in_flight: 50
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: true

jobs:
  - name: consul_z1
    templates:
    - name: consul
      release: consul
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    properties:
      consul: ~
      network: consul1
    persistent_disk: 0
    update:
      canaries: 0
      max_in_flight: 50

networks: (( merge ))

properties: {}
